root: ./

navigation:
  - title: Home
    path: /
  - title: Testnet
    path: /testnet
  - title: Litepaper (legacy)
    path: /litepaper

plugins:
  - highlight
  - search
  - github
  - expandable-chapters
  - back-to-top-button

pluginsConfig:
  github:
    url: https://github.com/sanyatsb/gensyn-docs-ru
  expandable-chapters: {}
  back-to-top-button:
    show: true
    position: right
